version: '3'

services:
  db:
    image: mariadb:10
    ports:
      - 3306:${MYSQL_PORT}
    # volumes:
      # - ./db/conf.d:/etc/mysql/conf.d
      # - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
    restart: on-failure

  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./:/usr/src/authorice
    networks:
      - backend
    restart: on-failure

networks:       
  backend:
    driver: bridge
